### ISSUE TITLE
READ THE NEEDFUL

### ISSUE THREAD

**Issue by kirtipndt12** [krupalhp2907/dashboard#13]
BUG LIFE CYCLE:
![Bug-Lifecycle](https://user-images.githubusercontent.com/46815975/88258026-c2207580-ccdc-11ea-950d-c63307efcca4.jpg)
@krupalhp2907

**Comment by krupalhp2907** [comment]
Duplicate of #12

**Comment by krupalhp2907** [comment]
Testing github #1

**Comment by krupalhp2907** [comment]
Close #14

**Comment by krupalhp2907** [comment]
#12 duplicate

**Comment by krupalhp2907** [comment]
dependencies of #12

**Comment by krupalhp2907** [comment]
duplicate of #12
this is some random text.
another random text

**Comment by krupalhp2907** [comment]
#12

**Comment by krupalhp2907** [comment]
duplicate of #12
see details
